name: Schedule Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "2,12,22,32,42,52 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger time
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          date -u
