name: Schedule Test

on:
  workflow_dispatch:

  schedule:
    - cron: "2,12,22,32,42,52 * * * *"
    timezone: 'America/New_York'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger time
        run: |
          echo "Schedule fired"
          date -u
